version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - msridhar
  ignore:
  - dependency-name: nebula.lint
    versions:
    - ">= 15.0.a, < 15.1"
  - dependency-name: nebula.lint
    versions:
    - ">= 16.0.a, < 16.1"
  - dependency-name: nebula.lint
    versions:
    - ">= 16.1.a, < 16.2"
  - dependency-name: nebula.lint
    versions:
    - ">= 16.2.a, < 16.3"
  - dependency-name: com.diffplug.eclipse.mavencentral
    versions:
    - 3.29.0
  - dependency-name: org.smali:dexlib2
    versions:
    - 2.5.0
    - 2.5.1
