#!/bin/bash -ex

REPO_ROOT_DIR="$(git rev-parse --show-toplevel)"

mapfile -t files < <(git diff --cached --name-only --diff-filter=ACMR | grep -Ei '\.java$')

join() {
  local IFS="$1"
  shift
  echo "$*"
}

if [ "${#files[@]}" -gt 0 ]; then
  comma_files=$(join , "${files[@]}")
  "${REPO_ROOT_DIR}/gradlew" goJF -DgoogleJavaFormat.include="$comma_files" >/dev/null 2>&1
  git add "${files[@]}"
fi
