
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Apr 05 20:51:34 EDT 2015
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NH = 11;
  public static final int CR = 22;
  public static final int T_OPT = 27;
  public static final int TE = 24;
  public static final int RS = 8;
  public static final int IP = 7;
  public static final int LP = 10;
  public static final int T_FORM = 28;
  public static final int TC_ = 25;
  public static final int R = 16;
  public static final int UL = 20;
  public static final int AU = 3;
  public static final int LG = 17;
  public static final int T_ROW = 29;
  public static final int DS = 5;
  public static final int I = 15;
  public static final int RE = 9;
  public static final int PP = 13;
  public static final int EOF = 0;
  public static final int AI = 4;
  public static final int B = 14;
  public static final int SM = 19;
  public static final int TXT = 26;
  public static final int DE = 6;
  public static final int SH = 12;
  public static final int error = 1;
  public static final int TS = 23;
  public static final int N_L = 21;
  public static final int NL = 18;
  public static final int TL = 2;
}

