#!/bin/sh -eux

case "$TRAVIS_OS_NAME" in
  (linux) headless=xvfb-run ;;
  (osx) headless= ;;
esac

case "$SUBMODULE_PREFIX" in
  (:*:*:)
    # native subsubcomponent: no Java code, so no Javadoc
    documentation=
    ;;
  (*)
    # Java subcomponent
    documentation=javadoc
    ;;
esac

# TRAVIS_JDK_VERSION is unset on Mac with JDK 8
MY_JDK_VERSION=${TRAVIS_JDK_VERSION:-}
if [ "$MY_JDK_VERSION" = "openjdk11" ]
then
    # only test WALA core on JDK 11 for now
    $headless ./gradlew --continue --no-build-cache --stacktrace \
              :com.ibm.wala.core.tests:test
else
    $headless ./gradlew --continue --no-build-cache --stacktrace \
	      verifyGoogleJavaFormat \
	      "$SUBMODULE_PREFIX"build \
	      ${documentation:+$SUBMODULE_PREFIX$documentation} \
	      lintGradle
fi
