#!/bin/sh -ex

xvfb-run mvn clean install -B -q

{
  set +x
  if [ -n "$AUTH_TOKEN" ]; then
    bash ./dependent-projects-trigger.sh "$AUTH_TOKEN"
  fi
  set -x
}

mvn javadoc:aggregate -B -q

{
  set +x
  if [ -n "$GH_TOKEN" ]; then
    bash ./upload-javascript.sh "$GH_TOKEN"
  fi
  set -x
}

./build-maven-jars.py 'install -Dgpg.skip'
